// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package sql

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ProcessorConfigConnectionString = "connectionString"
	ProcessorConfigDriver           = "driver"
	ProcessorConfigFields           = "fields"
	ProcessorConfigMode             = "mode"
	ProcessorConfigOutputField      = "outputField"
	ProcessorConfigQuery            = "query"
)

func (ProcessorConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ProcessorConfigConnectionString: {
			Default:     "",
			Description: "Database connection string",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ProcessorConfigDriver: {
			Default:     "postgres",
			Description: "SQL driver to use",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ProcessorConfigFields: {
			Default:     "",
			Description: "Fields to extract from record",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ProcessorConfigMode: {
			Default:     "transform",
			Description: "Processing mode",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ProcessorConfigOutputField: {
			Default:     "sql_result",
			Description: "Output field for enrichment mode",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ProcessorConfigQuery: {
			Default:     "",
			Description: "SQL query to execute",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
